In [ ]:
import numpy as np

In [ ]:
import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)

# Print the array
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

# Create an array of 10 ones
ones_array = np.ones(10)

# Print the array
print(ones_array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np

# Create an array of 10 fives
fives_array = np.full(10, 5)

# Print the array
print(fives_array)


[5 5 5 5 5 5 5 5 5 5]


In [ ]:
import numpy as np

# Create an array of integers from 10 to 50 (inclusive)
integers_array = np.arange(10, 51)

# Print the array
print(integers_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
import numpy as np

# Create an array of even integers from 10 to 50 (inclusive)
even_integers = np.arange(10, 51, 2)

# Print the array
print(even_integers)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
import numpy as np

fives_array = np.full(10, 5)

memory_size_bytes = fives_array.nbytes

print(f"Memory size of the array: {memory_size_bytes} bytes")


Memory size of the array: 80 bytes


In [ ]:
import numpy as np

# Method 1: Using np.arange and reshape

# Create a 1D array with values from 0 to 8 (9 elements)
arr = np.arange(9)

# Reshape the 1D array into a 3x3 matrix
matrix = arr.reshape(3, 3)

# Method 2: Using np.linspace

# Create evenly spaced values from 0 to 8 with 9 elements (including endpoints)
values = np.linspace(0, 8, 9)

# Reshape the 1D array into a 3x3 matrix
matrix = values.reshape(3, 3)

# Print the matrix
print(matrix)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [ ]:
import numpy as np

# Create a 3x3 identity matrix using np.eye
identity_matrix = np.eye(3)

# Print the matrix
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

# Generate a random number between 0 and 1
random_number = np.random.rand()

# Print the random number
print(random_number)


0.1128653221588446


In [ ]:
import numpy as np

# Generate an array of 25 random numbers from standard normal distribution
random_numbers = np.random.randn(25)

# Print the array
print(random_numbers)


[-0.24453941 -1.84310831 -2.15273758  0.01659324  0.64080451 -0.01008968
 -1.27690216 -0.76349859  0.85606462  1.26379283 -0.31165158  1.50052011
  0.67431069 -0.17933254  0.08613937 -0.49438852  0.52365136 -0.76839646
 -0.2368532  -1.18353536  0.40450003 -0.7915092   1.92651517 -0.57802909
  1.61313876]


In [ ]:
import numpy as np

rows = 10
cols = 10

matrix = np.zeros((rows, cols))

for i in range(rows):
  for j in range(cols):
    matrix[i, j] = 0.01 + 0.01 * (i * cols + j)

print(matrix)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
import numpy as np

# Number of points
num_points = 20

# Starting and ending points
start = 0
end = 1

# Create linearly spaced points
linear_spaced_points = np.linspace(start, end, num_points)

# Print the array
print(linear_spaced_points)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np

# تحديد المصفوفة الأصلية
arr = np.arange(1, 26).reshape(5, 5)

# استخراج الجزء السفلي الأيمن من المصفوفة
sub_array = arr[2:5, 1:5]

# طباعة المصفوفة الفرعية
print(sub_array)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
import numpy as np

# إنشاء المصفوفة الأساسية
arr = np.arange(1, 26).reshape(5, 5)

# تحديد موقع الرقم 20
row_index = 3  # يبدأ الترقيم من 0
column_index = 4

# طباعة الرقم 20
print(arr[row_index, column_index])


20


In [ ]:
import numpy as np

# تحديد المصفوفة الأصلية
arr = np.arange(1, 26).reshape(5, 5)

# استخراج الجزء السفلي الأيمن من المصفوفة
sub_array = arr[0:3, 1:2]

# طباعة المصفوفة الفرعية
print(sub_array)


[[ 2]
 [ 7]
 [12]]


In [ ]:
import numpy as np

# تحديد المصفوفة الأصلية
arr = np.arange(1, 26).reshape(5, 5)

# استخراج الجزء السفلي الأيمن من المصفوفة
sub_array = arr[4:5, 0:5]

# طباعة المصفوفة الفرعية
print(sub_array)


[[21 22 23 24 25]]


In [2]:
import numpy as np

# Create a 5x5 matrix filled with numbers from 1 to 25 (reshape from a 1D array)
mat = np.arange(1, 26).reshape(5, 5)


# Get the sum of all the values in the matrix
sum_of_all_values = mat.sum()

# Print the sum
print("Sum of all values in the matrix:", sum_of_all_values)


Sum of all values in the matrix: 325


In [3]:
import numpy as np

# Create a 5x5 matrix filled with numbers from 1 to 25 (reshape from a 1D array)
mat = np.arange(1, 26).reshape(5, 5)

# Standard deviation of the matrix (all elements treated as a 1D array)
std_dev = np.std(mat)

# Print the standard deviation
print("Standard deviation of all values in the matrix:", std_dev)


Standard deviation of all values in the matrix: 7.211102550927978


In [4]:
import numpy as np

# Create a 5x5 matrix filled with numbers from 1 to 25 (reshape from a 1D array)
mat = np.arange(1, 26).reshape(5, 5)

# Get the sum of all columns
column_sums = mat.sum(axis=0)  # Sum along axis 0 (columns)

# Print the column sums
print("Sum of each column:", column_sums)


Sum of each column: [55 60 65 70 75]


In [5]:
import numpy as np

# Create a 10x10 matrix of zeros
matrix = np.zeros((10, 10))

# Set the border elements to 1
matrix[0, :] = 1  # Top row
matrix[-1, :] = 1  # Bottom row
matrix[:, 0] = 1  # Left column
matrix[:, -1] = 1  # Right column

# Print the matrix
print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
import numpy as np

# Define the arrays
x1 = np.array([0, 2, 2, 2, 4, 5, 1, 4, 8, 5])
x2 = np.array([2, 2, 3, 4, 7, 4, 6, 9, 4, 8])

# Find common elements using intersection
common_elements = np.intersect1d(x1, x2)

# Print the common elements
print("Common elements between x1 and x2:", common_elements)


Common elements between x1 and x2: [2 4 8]


In [8]:
import numpy as np

x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

flattened_x = x.flatten()  # Creates a copy and flattens
print(flattened_x)  # Output: [ 1  2  3  4  5  6  7  8  9 10 11 12]



[ 1  2  3  4  5  6  7  8  9 10 11 12]
